name: S3Workflows
on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Updated to the latest version
        with: 
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./path/to/your/project # Add this line if your package.json is not in the root directory

      - name: Build
        run: npm run build
        working-directory: ./path/to/your/project # Add this line if your package.json is not in the root directory

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2 # Updated to the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload to S3
        run: aws s3 sync build s3://shikabala
        working-directory: ./path/to/your/project/build # Ensure this path is correct

      - name: Publish Message To SNS Subscribers
        run: aws sns publish --topic-arn <your-sns-topic-arn> --message "New Version Is Released"
